export const INCRIMENT_COUNTER = "INCRIMENT_COUNTER";
export const DECRIMENT_COUNTER = "DECRIMENT_COUNTER";
export const GET_MEDICINES = "GETMEDICINES";
// export const ERRORMEDICINES = "ERRORMEDICINES"