export const INCRIMENT_COUNTER = "INCRIMENT_COUNTER";
export const DECRIMENT_COUNTER = "DECRIMENT_COUNTER";
export const GET_LOADING = "GET_LOADING";
export const GET_ERROR = "GET_ERROR";
export const GET_MEDICINES = "GET_MEDICINES";
// export const ERRORMEDICINES = "ERRORMEDICINES"